<a href="https://colab.research.google.com/github/futugyou/pyproject/blob/master/google_colab/torch_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install torch

In [ ]:
import torch

torch.__version__

In [ ]:
torch.cuda.is_available()

In [23]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(
            # layer 1
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),
            # layer 2
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),
            # output layer
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        return self.layers(x)

In [27]:
model = NeuralNetwork(50, 3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [28]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Number of parameters: {num_params}")

Number of parameters: 2213


In [26]:
print(model.layers[0].weight)

Parameter containing:
tensor([[ 0.0476,  0.0857, -0.0824,  ...,  0.0505,  0.0280, -0.0636],
        [-0.0806, -0.1262, -0.1134,  ..., -0.0019, -0.0738, -0.0054],
        [ 0.1375, -0.1107,  0.0567,  ...,  0.0729,  0.0056, -0.1174],
        ...,
        [-0.0869, -0.0323, -0.0135,  ..., -0.0495, -0.0653, -0.0196],
        [ 0.1260, -0.0271,  0.0542,  ..., -0.1228, -0.0481, -0.0063],
        [-0.0778,  0.0346, -0.0602,  ..., -0.1046,  0.0447,  0.1069]],
       requires_grad=True)


In [29]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [30]:
torch.manual_seed(123)
x = torch.rand((1, 50))
out = model(x)
print(out)

tensor([[-0.0532, -0.0240, -0.0347]], grad_fn=<AddmmBackward0>)


In [31]:
with torch.no_grad():
    out = model(x)
print(out)

tensor([[-0.0532, -0.0240, -0.0347]])


In [32]:
with torch.no_grad():
    out = torch.softmax(model(x), dim=1)
print(out)

tensor([[0.3281, 0.3378, 0.3342]])
